---
- name: Demo on vars
  hosts: all
  vars:
    URL: "play.google.com"
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "Value of the url is {{ URL }}"

    - name: printing play variables
      ansible.builtin.debug:
        msg: "{{ URL }}"

    - name: printing local variables
      ansible.builtin.debug:
        msg: "value of the task variable is {{ URL }}"
      vars:
        URL: "task.google.com"


- name: Demo on vars on play2
  hosts: all
    URL: "play2.google.com"
  tasks:
    - name: printing play variable on play2
      ansible.builtin.debug:
        msg: "Value of the url is {{ URL }}"
