- name: Demo on using shell module
  hosts: all
  tasks:
    - name: Running uptime command
      ansible.builtin.shell: uptime
      register: OUT
      
    - name: printing uptime output
      ansible.builtin.debug:
      msg: "{{ OUT.stdout }}"
